# Generated by Django 2.0.6 on 2020-12-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='orders',
            field=models.IntegerField(default=1, verbose_name='图片排序'),
        ),
    ]
